import { Rubik } from "next/font/google";
import "./globals.css";
import Theme from "./context/ThemeProvider";
const rubik = Rubik({
  subsets: ["latin", "arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
        <body className={rubik.className}>{children}</body>
      </Theme>
    </html>
  );
}
